  -- Create a table from census data, aggregating the data to the blockgroup, in AZ
CREATE OR REPLACE TABLE
  `az-voter-file.AVPv2.blockAggregates`AS(
  SELECT
    geo_id AS census_block_,
    total_pop,
    households,
    male_pop,
    female_pop,
    median_age,
    white_pop,
    pop_16_over,
    black_pop,
    asian_pop,
    hispanic_pop,
    amerindian_pop,
    other_race_pop,
    two_or_more_races_pop,
    not_hispanic_pop,
    median_income,
    income_per_capita,
    income_less_10000,
    income_10000_14999,
    income_15000_19999,
    income_20000_24999,
    income_25000_29999,
    income_30000_34999,
    income_35000_39999,
    income_40000_44999,
    income_45000_49999,
    income_50000_59999,
    income_60000_74999,
    income_75000_99999,
    income_100000_124999,
    income_125000_149999,
    income_150000_199999,
    income_200000_or_more,
    housing_units,
    occupied_housing_units,
    housing_units_renter_occupied,
    vacant_housing_units,
    vacant_housing_units_for_rent,
    vacant_housing_units_for_sale,
    mobile_homes,
    housing_built_2005_or_later,
    housing_built_2000_to_2004,
    housing_built_1939_or_earlier,
    median_year_structure_built,
    married_households,
    nonfamily_households,
    family_households,
    median_rent,
    percent_income_spent_on_rent,
    million_dollar_housing_units,
    aggregate_travel_time_to_work,
    commuters_by_public_transportation,
    associates_degree,
    bachelors_degree,
    high_school_diploma,
    less_one_year_college,
    masters_degree,
    one_year_more_college,
    employed_pop,
    unemployed_pop,
    centroids.centroid_longitude AS centroid_longitude,
    centroids.centroid_latitude AS centroid_latitude,
  FROM
    `bigquery-public-data.census_bureau_acs.blockgroup_2018_5yr` AS a
  JOIN
    `az-voter-file.AVPv2.centroids` AS centroids
  ON
    a.geo_id = centroids.census_block);